In [4]:
import numpy as np
import pandas as pd

# 배열의 정보를 확인하기 위한 함수 정의

def aryinfo(ary) :
    print('type      - ' , type(ary))
    print('shape     - ' , ary.shape)
    print('dimension - ' , ary.ndim)
    print('dtype     - ' , ary.dtype)
    print()
    print('data - ')
    print(ary)

- 배열 연결(concatenate)
- hstack(), vstack(), dstack(), r_, c_, tile

In [16]:
print('hstack - 행의 수가 같은 두 개 이상의 배열을 연결')
print()

ary01 = np.ones((3,4))
print(ary01)

print()

ary02 = np.zeros((3,5))
print(ary02)

print()

# 행의 수가 같을 경우 결합 가능
print(np.hstack([ary01, ary02]))


hstack - 행의 수가 같은 두 개 이상의 배열을 연결

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]]


In [20]:
print('vstack - 열의 수가 같은 두 개 이상의 배열을 연결')
print()

ary01 = np.ones((3,4))
print(ary01)

print()

ary02 = np.zeros((3,4))
print(ary02)

print()

print(np.vstack([ary01, ary02]))

vstack - 열의 수가 같은 두 개 이상의 배열을 연결

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
print('dstack - 행과 열이 아닌 깊이 방향으로 배열을 배열을 연결')
print('차원이 추가되는 것이기 때문에 행과 열이 같아야한다.')
print('행 개수 : 차원 수, 열 마다 짝지음')
print()

ary01 = np.ones((3,4))
print(ary01)

print()

ary02 = np.zeros((3,4))
print(ary02)

print()

print(np.dstack([ary01, ary02]))
aryinfo(np.dstack([ary01, ary02]))

dstack - 행과 열이 아닌 깊이 방향으로 배열을 배열을 연결

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
type      -  <class 'numpy.ndarray'>
shape     -  (3, 4, 2)
dimension -  3
dtype     -  float64

data - 
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [28]:
print('stack - 사용자가 지정한 차원(축 : x, y) 배열을 연결')
print('축 방향 : axis = 0 default')
print()

ary01 = np.ones((3,4))
print(ary01)

print()

ary02 = np.zeros((3,4))
print(ary02)

print('--------------------')

aryinfo(np.stack([ary01, ary02] , axis = 0))
print()
aryinfo(np.stack([ary01, ary02] , axis = 1))

stack - 사용자가 지정한 차원(축 : x, y) 배열을 연결
축 방향 : axis = 0 default

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------
type      -  <class 'numpy.ndarray'>
shape     -  (2, 3, 4)
dimension -  3
dtype     -  float64

data - 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

type      -  <class 'numpy.ndarray'>
shape     -  (3, 2, 4)
dimension -  3
dtype     -  float64

data - 
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


In [30]:
print('r_[] - 인덱서 == hstack 열이 증가하는 배열 연결')
print('c_[] - 인덱서 == 배열의 차원 증가 후 배열 연결')

print(np.r_[np.array([1,2,3]) , np.array([4,5,6])])
print()
print(np.c_[np.array([1,2,3]) , np.array([4,5,6])])

r_[] - 인덱서 == hstack 열이 증가하는 배열 연결
[1 2 3 4 5 6]

[[1 4]
 [2 5]
 [3 6]]


In [34]:
print('tile - 동일한 배열을 반복하여 연결')
ary = np.array([[1,2,3] , [4,5,6]])
aryinfo(ary)
print()

# ary 배열을 타일형식으로 3행3열로 반복
print( np.tile(ary , (3,3)))

tile - 동일한 배열을 반복하여 연결
type      -  <class 'numpy.ndarray'>
shape     -  (2, 3)
dimension -  2
dtype     -  int32

data - 
[[1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [ ]:
# 위 결과가 나올 수 있도록 함수를 이용하여 작성해 보세요~~~
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])


In [91]:
ary_01 = np.zeros((3,3))
print(ary_01)
print()

ary_02 = np.ones((3,2))
print(ary_02)
print()

ary_03 = np.arange(10,160,10).reshape(3,5)
print(ary_03)
print()



# 1
step_01 = np.hstack([ary_01 , ary_02])
print(step_01)
aryinfo(step_01)

print()
print()
print()

# 2 
step_02 = np.vstack([step_01 , ary_03 ])
print(step_02)
print()
print()
print()

# 3
step_03 = np.tile(step_02 , (2,1))
print(step_03)
print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]

[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]
type      -  <class 'numpy.ndarray'>
shape     -  (3, 5)
dimension -  2
dtype     -  float64

data - 
[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]



[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]



[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]



In [54]:
np.arange(10,51,10)

array([10, 20, 30, 40, 50])

#### delete()
- axis 기준행과 열을 삭제 할 수 있다. : axis = 0(행) , 1(열)
- axis 지정하지 않으면 1차원 변환 후 삭제
- 원본 배열을 변경하지 않고 새로운 배열 return

In [95]:
ary = np.random.randint(0 , 10 , (3,4))
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shape     -  (3, 4)
dimension -  2
dtype     -  int32

data - 
[[5 6 6 5]
 [8 5 6 8]
 [3 1 3 7]]


In [106]:
ary_new = np.delete(ary , 1 , axis = 1)
aryinfo(ary_new)

type      -  <class 'numpy.ndarray'>
shape     -  (3, 3)
dimension -  2
dtype     -  int32

data - 
[[5 6 5]
 [8 6 8]
 [3 3 7]]


- loadtxt() : 파일 입출력 가능

In [119]:
raw_data = np.loadtxt('C:/Users/a/data/02. crime_in_Seoul.csv' , dtype=np.object , skiprows=1)
aryinfo(raw_data)
print()
print()
print(raw_data[0])
print()
print('-'*50)
ary = raw_data[ : , np.newaxis]
aryinfo(ary)
print('this - ' , ary[0])

type      -  <class 'numpy.ndarray'>
shape     -  (31,)
dimension -  1
dtype     -  object

data - 
['중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170"'
 '종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070"'
 '남대문서,1,0,6,4,65,46,"1,153",382,869,794'
 '서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711"'
 '혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861'
 '용산서,5,5,14,14,194,173,"1,557",587,"2,050","1,704"'
 '성북서,2,2,2,1,86,71,953,409,"1,194","1,015"'
 '동대문서,5,5,13,13,173,146,"1,981",814,"2,548","2,227"'
 '마포서,8,8,14,10,294,247,"2,555",813,"2,983","2,519"'
 '영등포서,14,12,22,20,295,183,"2,964",978,"3,572","2,961"'
 '성동서,4,4,9,8,126,119,"1,607",597,"1,612","1,395"'
 '동작서,5,5,9,5,285,139,"1,865",661,"1,910","1,587"'
 '광진서,4,4,14,26,240,220,"3,026","1,277","2,625","2,180"'
 '서부서,2,2,2,1,70,59,819,293,"1,192","1,038"'
 '강북서,7,8,14,13,153,126,"1,434",618,"2,649","2,348"'
 '금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776"'
 '중랑서,13,12,11,9,187,148,"2,135",829,"2,847","2,407"'
 '강남서,3,3,15,12,300,225,"2,411",984,"2

C:\Users\a\AppData\Local\Temp\ipykernel_9052\3603863930.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  raw_data = np.loadtxt('C:/Users/a/data/02. crime_in_Seoul.csv' , dtype=np.object , skiprows=1)


#### 배열의 연산
- vectorized operator(벡터화 연산)
- borad casting : 벡터와 행렬의 연사을 위해서는 크기가 같아야한다.
- 그렇다면 서로다른 크기를 가진 두 배열의 연산은 가능할까?

In [129]:
ary01 = np.arange(1 , 10001)
ary02 = np.arange(10001 , 20001)

ary01 + ary02

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [132]:
# 비어있는 배열 생성


result = np.zeros_like(ary01)
for idx in range(len(ary01)) :
    result[idx] = ary01[idx] + ary02[idx]

print('answer')
print(result)




answer
[10002 10004 10006 ... 29996 29998 30000]


In [136]:
%%time
result = np.zeros_like(ary01)
result = ary01 + ary02
print('answer')
print(result)

answer
[10002 10004 10006 ... 29996 29998 30000]
CPU times: total: 0 ns
Wall time: 1 ms


In [142]:
ary01 = np.array([1,2,3,4])
ary02 = np.array([4,3,2,4])
ary03 = np.array([11,12,13,4])
print()
print('배열의 모든 원소가 같은지를 비교하고 싶다면 ? - all()')

print(np.all(ary01 == ary02))
print(ary01 in ary02)

print(np.all(ary01 == ary03))
print(ary01 in ary03)







배열의 모든 원소가 같은지를 비교하고 싶다면 ? - all()
False
True
False
True


In [144]:
ary01 = np.arange(12).reshape(-1,4)
ary01

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
ary02 = np.arange(3)
ary02

array([0, 1, 2])

In [149]:
ary01 + ary02[ : , np.newaxis]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

#### 차원축소 (dimension reduction)
- 기술적 통계함수(min, max, sum, mean, median, std, var etx...)
- all , any
- 인덱스를 리턴하는 차원축소 함수 : argmin, argmx



In [157]:
ary = np.array([1,2,3,4,5])
print('data - ' , ary , ary.shape , ary.ndim)
print('sum - '  , np.sum(ary) , type(np.sum(ary)))
print('sum - '  , ary.sum() , type(ary.sum()))
print()
print('sum - '  , np.min(ary) , type(np.min(ary)))
print('min - '  , ary.min()   , type(ary.min()))
print()
print('max - '  , np.max(ary)   , type(np.max(ary)))
print('max - '  , ary.max()     , type(ary.max()))
print()
print('mean - '  , np.mean(ary)   , type(np.mean(ary)))
print('mean - '  , ary.mean()     , type(ary.mean()))
print()
print('median - '  , np.median(ary)   , type(np.median(ary)))
# print('median - '  , ary.median()     , type(ary.median())) -- error!




data -  [1 2 3 4 5] (5,) 1
sum -  15 <class 'numpy.int32'>
sum -  15 <class 'numpy.int32'>

sum -  1 <class 'numpy.int32'>
min -  1 <class 'numpy.int32'>

max -  5 <class 'numpy.int32'>
max -  5 <class 'numpy.int32'>

mean -  3.0 <class 'numpy.float64'>
mean -  3.0 <class 'numpy.float64'>

median -  3.0 <class 'numpy.float64'>


In [164]:
# 중요 함수
# 최소 인덱싱 번호
# 최대 인덱싱 번호

ary = np.array([1,2,3,4,5])
ary

print('index - ' , np.argmin(ary))
min_idx = np.argmin(ary)
print('min_idx' , min_idx , ary[min_idx])
# min_idx = 0 , ary[0]

print('max index - ' , np.argmax(ary) , ary[np.argmax(ary)])

print()
print('all - ')
print( np.all([True, False, True]))
print('any - ')
print( np.any([True, False, True]))

index -  0
min_idx 0 1
max index -  4 5

all - 
False
any - 
True


- 연산의 대상이 2차원 행렬(matrix) 이라면?
- axis 방향 설정이 중요

In [167]:
ary = np.arange(1, 21, 1).reshape(4, -1)
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shape     -  (4, 5)
dimension -  2
dtype     -  int32

data - 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [176]:
print('sum - ')
print('sum - ' , np.sum(ary) , type(np.sum(ary)))
print('row sum - ' , np.sum(ary , axis = 1))
print('col sum - ' , np.sum(ary , axis = 0))

sum - 
sum -  210 <class 'numpy.int32'>
row sum -  [15 40 65 90]
col sum -  [34 38 42 46 50]


### print('min , argmin - index , max , argmax - index ,mean , median')

In [184]:
print('min - ')
print('min - ' , np.min(ary) , type(np.min(ary)) )
print('argmin - ')
print('argmin - ' , np.argmin(ary) , type(np.argmin(ary)))
print('max - ')
print('max - ' ,     np.max(ary) , type(np.max(ary)))

min - 
min -  1 <class 'numpy.int32'>
argmin - 
argmin -  0 <class 'numpy.int64'>
max - 
max -  20 <class 'numpy.int32'>


In [187]:
ary = np.random.randint(0,10000000 , (5,6))
ary

array([[98270958, 89813175, 63024948, 73182408, 25951688, 89481980],
       [69533106, 31948545, 19492427, 43864457, 68222885, 38423008],
       [34879294, 78921569, 82170318, 81542826, 16637202, 57385805],
       [52310016, 17647809, 24703802, 59306735, 68454418, 58795850],
       [43985298, 97125328, 74848714, 51924568, 92777255, 25838324]])

In [212]:
print('전체의 최댓값 - ', ary.max())
print(np.max(ary))

print('행의 합      '   , np.sum(ary , axis =1))
print('행의 합 for -hstack-')
print('hstack' , np.hstack([ary[idx].sum() for idx in range(ary.shape[0])]))

전체의 최댓값 -  98270958
98270958
행의 합       [439725157 271484428 351537014 281218630 386499487]
행의 합 for -hstack-
hstack [439725157 271484428 351537014 281218630 386499487]


In [192]:
len(ary)
ary[0].sum()

439725157

In [230]:
print('각 행의 최댓값' , np.hstack([ary[idx].sum() for idx in range(ary.shape[0])]))
print()
for i in range(len(ary)) :
    print(np.max(ary[i , :]))
    
print()
print('각 열의 평균' , np.hstack([ary[: , idx].mean() for idx in range(ary.shape[1])]))
print()
for i in range(len(ary)) :
    print(np.mean(ary[: , i]))
    
print()
print('각 열의 최솟값' , np.hstack([ary[: , idx].min() for idx in range(ary.shape[1])]))
print()
for i in range(len(ary)) :
    print(np.min(ary[: , i]))


각 행의 최댓값 [439725157 271484428 351537014 281218630 386499487]

98270958
69533106
82170318
68454418
97125328

각 열의 평균 [59795734.4 63091285.2 52848041.8 61964198.8 54408689.6 53984993.4]

59795734.4
63091285.2
52848041.8
61964198.8
54408689.6

각 열의 최솟값 [34879294 17647809 19492427 43864457 16637202 25838324]

34879294
17647809
19492427
43864457
16637202


- 정렬 : sort
- ary.sort() : 원본에 대한 변경(inplace = True)
- np.sort(ary) : 원본에 대한 변경 X(inplace = False)
- inplace - 실제로는 사용 거의 불가


In [248]:
ary = np.arange(10)
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [261]:
# 배열 순서 섞기
np.random.shuffle(ary)
ary

array([1, 4, 5, 9, 6, 3, 0, 8, 2, 7])

In [244]:
np.sort(ary)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [245]:
ary

array([6, 7, 0, 4, 9, 3, 5, 1, 8, 2])

In [260]:
ary.sort()
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [262]:
np.sort(ary)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [264]:
print('행렬에 대한 정렬 - ')
ary = np.random.randint(0 , 17 , (4,4))
ary

행렬에 대한 정렬 - 


array([[ 7, 13,  6,  1],
       [ 5, 14,  2,  2],
       [ 3,  2,  5, 15],
       [ 8, 10,  4, 12]])

In [265]:
print('행 정렬')
np.sort(ary , axis = 1)

array([[ 1,  6,  7, 13],
       [ 2,  2,  5, 14],
       [ 2,  3,  5, 15],
       [ 4,  8, 10, 12]])

In [267]:
print('열 정렬')
np.sort(ary , axis = 0)

열 정렬


array([[ 3,  2,  2,  1],
       [ 5, 10,  4,  2],
       [ 7, 13,  5, 12],
       [ 8, 14,  6, 15]])

- 만약, 정렬된 인덱스를 필요로 한다면?
- np.argsort()

In [273]:
ary = np.array([4,3,5,7])
ary

array([4, 3, 5, 7])

In [279]:
# sort 된 순으로 인덱싱이 되어있다.

ary_idx = np.argsort(ary)
ary_idx

array([1, 0, 2, 3], dtype=int64)

In [280]:
ary[ary_idx]

array([3, 4, 5, 7])

In [282]:
ary[ary_idx][::-1]

array([7, 5, 4, 3])

In [285]:
ary = np.random.randint(1, 17, (4,4))
ary

array([[ 3,  4, 15,  6],
       [ 2,  6,  8,  1],
       [ 7,  1, 15, 14],
       [ 3, 14, 16,  3]])

In [290]:
ary.argsort(axis = -1)

array([[0, 1, 3, 2],
       [3, 0, 1, 2],
       [1, 0, 3, 2],
       [0, 3, 1, 2]], dtype=int64)

In [295]:
np.argsort(ary , axis = 0)

array([[1, 2, 1, 1],
       [0, 0, 0, 3],
       [3, 1, 2, 0],
       [2, 3, 3, 2]], dtype=int64)

### 2차원 이상에서의 index 정렬은 특정 행/열을 추출해야만 가능하다

- 연결 보다는 행 추가 , 컬럼 추가 하는 방법
- np.concatenate()

In [297]:
ary = np.array([[1,2,3],[4,5,6]])
ary

array([[1, 2, 3],
       [4, 5, 6]])

In [301]:
print('행 추가 - ')
new_row = np.array([7,8,9])
print(np.concatenate((ary , new_row[np.newaxis , :]) , axis = 0))
print(np.concatenate((ary , new_row.reshape(1,3)) , axis = 0) )


행 추가 - 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [303]:
new_row.reshape(1,3)
aryinfo(new_row.reshape(1,3))

type      -  <class 'numpy.ndarray'>
shape     -  (1, 3)
dimension -  2
dtype     -  int32

data - 
[[7 8 9]]


In [313]:
print('열 추가 - ')
new_col = np.array([7,8,9,10])
print(np.concatenate((ary , new_col[: , np.newaxis].reshape(2,2)) , axis = 1))
print(np.concatenate((ary , new_col.reshape(2,2)) , axis = 1) )


열 추가 - 
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [314]:
print('문제 - 200개의 표준정규분표 샘플을 만들어서 내림차순으로 상위 5%까지의 결과를 출력한다.')


문제 - 200개의 표준정규분표 샘플을 만들어서 내림차순으로 상위 5%까지의 결과를 출력한다.


In [322]:
pb = np.random.randint(1,1000 , 200)
pb

array([592, 348, 175,  77, 447, 904,  16, 363, 860, 721, 651, 167, 740,
       241, 992, 857, 303, 410,  26, 998, 157,  63, 309, 343,   5, 137,
       790, 439, 641, 597,  92, 309, 741, 198, 893, 608, 671, 487, 687,
       859,  34, 597,   6, 296, 283, 103,  86, 737, 259, 488, 769, 931,
       127, 970, 198, 361, 575, 270, 143, 916, 584, 693, 506, 599, 492,
       779, 652, 679, 745,  76, 264, 782,  48, 760, 436, 627, 171, 301,
       344, 611, 739, 821, 574,  99, 983, 387, 260, 574, 857, 666,  61,
       228, 347, 207, 493, 424, 529, 965,  20, 380, 439, 195, 635, 205,
       875, 409, 311, 668, 924, 473, 403, 214, 868, 718, 169, 475, 160,
       474, 777, 483, 210, 686, 300, 970, 100,  80,  27, 166, 836, 166,
       199, 495, 395,  79, 924, 490, 802, 323, 876, 543, 372, 470, 354,
       491, 986,  65, 211,  89, 557, 979, 113, 192, 941, 510, 397, 543,
       163,  43, 239, 794, 726, 974, 659, 828, 293, 610, 439, 489, 915,
       784, 651, 660, 618, 943, 442, 272, 629, 616, 639, 917, 14

In [323]:
pb_resort = np.sort(pb)[::-1]
pb_resort

array([999, 998, 992, 986, 983, 979, 974, 970, 970, 965, 943, 941, 931,
       924, 924, 917, 916, 915, 904, 893, 876, 875, 868, 868, 863, 860,
       859, 857, 857, 855, 836, 828, 821, 818, 802, 801, 794, 790, 784,
       782, 779, 777, 769, 762, 760, 745, 741, 740, 739, 737, 726, 721,
       718, 693, 687, 686, 683, 679, 671, 668, 666, 660, 659, 652, 651,
       651, 641, 639, 635, 629, 627, 618, 616, 611, 610, 608, 599, 597,
       597, 592, 584, 575, 574, 574, 557, 543, 543, 529, 510, 506, 495,
       493, 492, 491, 490, 489, 488, 487, 483, 475, 474, 473, 470, 453,
       447, 446, 442, 439, 439, 439, 436, 424, 415, 410, 409, 403, 397,
       395, 394, 387, 380, 372, 367, 363, 361, 354, 348, 347, 344, 343,
       323, 312, 311, 309, 309, 303, 301, 300, 296, 293, 283, 272, 271,
       270, 264, 260, 259, 244, 241, 239, 228, 219, 214, 211, 210, 207,
       205, 199, 198, 198, 195, 192, 175, 171, 169, 167, 166, 166, 163,
       160, 157, 151, 148, 143, 142, 137, 127, 113, 103, 100,  9

In [326]:
pb_resort[ : int(0.05*len(pb_resort))]

array([999, 998, 992, 986, 983, 979, 974, 970, 970, 965])

In [328]:
ary = np.random.randn(200)
ary

array([ 8.18735612e-01, -8.77696328e-02, -5.79561324e-01,  5.96693404e-01,
        5.97892804e-01,  3.95487918e-01, -9.55863268e-01,  8.65715648e-01,
       -5.10493388e-01, -7.94135754e-01, -3.91041584e-01,  7.87837951e-01,
       -5.88402268e-01, -2.85681124e-01, -8.64101168e-01, -1.08235825e+00,
        1.10889274e+00, -1.18634836e-01, -9.04810512e-01, -1.10344946e-02,
        9.39942862e-01,  9.09366653e-01,  7.59476060e-01,  2.33801804e-01,
        2.78774627e-01,  3.31881071e-01,  5.29161990e-01,  4.62696984e-01,
       -1.28936833e+00,  1.76908054e-01,  4.43053705e-01, -1.86094753e+00,
        4.76887558e-01, -8.59530451e-01,  6.38707036e-02,  2.72206804e-01,
       -7.32771834e-01,  9.80617634e-01, -1.93070783e+00,  4.25886948e-01,
       -1.51645901e+00,  4.78905450e-01,  1.49854028e+00,  5.67511587e-01,
        1.22899448e+00, -6.92436716e-01, -3.19171566e-01, -1.26242419e+00,
        1.45822559e+00,  4.15905340e-01,  3.22133314e-01,  1.46773173e-01,
       -2.71434180e-01, -

- space

In [331]:
ary = np.array([[1,2,3,4],[100,89,90,79],[60,70,80,99]])
aryinfo(ary)
print()
print()
print('두번째 행을 국어점수로 가정할 때, 국어 점수를 기준으로 열을 정렬한다면?')

type      -  <class 'numpy.ndarray'>
shape     -  (3, 4)
dimension -  2
dtype     -  int32

data - 
[[  1   2   3   4]
 [100  89  90  79]
 [ 60  70  80  99]]




In [339]:
ary[: , ary[1 , :].argsort()]

array([[  4,   2,   3,   1],
       [ 79,  89,  90, 100],
       [ 99,  70,  80,  60]])

In [341]:
print('case02')
answer = np.argsort(ary)[1][::-1]
print(answer)

case02
[0 2 1 3]
