#### Numpy 학습 목표
- 배열 데이터 타입(인공지능 사영되는 데이터의 타입)
- 생성 방벙 , 활용 방법
- 통계에 관련된 다양한 함수를 지원

##### 배열 (벡터화 연산 , 행렬의 벡터화 연산)
- 리스트와 차이가 있다(배열의 모든 원소는 같은 자료형)
- 원소의 개수를 바꿀 수 없다.(resizing X)
- 배열의 차원 , 크기 , 타입 (ndim , shpae , dtype)

In [23]:
import numpy  as np
import pandas as pd

In [243]:
# 배열의 정보를 확인하기 위한 함수 정의
def aryinfo(ary) :
    print('type      - ' , type(ary))
    print('shape     - ' , ary.shape)
    print('dimension - ' , ary.ndim)
    print('dtype     - ' , ary.dtype)
    print()
    print('data - ')
    print(ary)

- 배열 객체를 생성할 때 사용하는 함수 : array() , arange() , reshape()

In [25]:
ary = np.array([1,2,3,4,5,6,7,8,9] , dtype = np.object)

C:\Users\a\AppData\Local\Temp\ipykernel_3504\29025421.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ary = np.array([1,2,3,4,5,6,7,8,9] , dtype = np.object)


In [22]:
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (9,)
dimension -  1
dtype     -  object

data - 
[1 2 3 4 5 6 7 8 9]


In [32]:
data = [1,2,3,4,5,6,7,8,9]
print('type - ' , type(data))
print()
data * 2
print()
result = []
for value in data :
    result.append(value * 2)
    
print(result)
print()

result = [value*2  for valuei in data]

print()
print()

print(ary * 2)


type -  <class 'list'>


[2, 4, 6, 8, 10, 12, 14, 16, 18]



[2 4 6 8 10 12 14 16 18]


- 산술 , 비교 , 논리

In [34]:
ary01 = np.array([1, 2, 3, 4, 5])
ary02 = np.array([10, 20, 30, 40, 50])
print('type - ' , type(ary01) , type(ary02))

type -  <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [36]:
print('산술연산 - ')
print(ary01 * ary02)

[ 10  40  90 160 250]


In [40]:
print('비교연산 - ')
boolean_masking = (ary01 == 2)
print(boolean_masking , type(boolean_masking) , boolean_masking[0])
print(ary01[boolean_masking])

비교연산 - 
[False  True False False False] <class 'numpy.ndarray'> False
[2]


In [42]:
print('논리연산 - ')
print((ary01 == 2) & (ary02 > 10))
print((ary01 == 2) | (ary02 > 10))

논리연산 - 
[False  True False False False]
[False  True  True  True  True]


- 2차원 배열(matrix - 행렬) : list of list  
- N-dimensional Array

In [56]:
print('2 * 3 의 배열을 생성한다면? -')
ary = np.array([[1,2,3],[4,5,6]])
aryinfo(ary)

print()
print('len() - ' , len(ary))
print('len() - ' , len(ary[0]))
print('len() - ' , len(ary[1]))


2 * 3 의 배열을 생성한다면? -
type      -  <class 'numpy.ndarray'>
shaqe     -  (2, 3)
dimension -  2
dtype     -  int32

data - 
[[1 2 3]
 [4 5 6]]

len() -  2
len() -  3
len() -  3


In [57]:
print('3 * 4 의 배열을 2개 생성')
ary = np.array([[[1,2,3,4] , [5,6,7,8] , [9,10,11,12]], [['a','b','c','d'] , ['e','f','g','h'] , ['i','j','j','l']]])

aryinfo(ary)
print('len() - ' , len(ary))
print('len() - ' , len(ary[0]))

print('len() - ' , len(ary[0][0]))

3 * 4 의 배열을 2개 생성
type      -  <class 'numpy.ndarray'>
shaqe     -  (2, 3, 4)
dimension -  3
dtype     -  <U11

data - 
[[['1' '2' '3' '4']
  ['5' '6' '7' '8']
  ['9' '10' '11' '12']]

 [['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']
  ['i' 'j' 'j' 'l']]]
len() -  2
len() -  3
len() -  4


- astype() : 요소의 타입을 변경할 때 사용

In [61]:
aryinfo(ary.astype(object))

type      -  <class 'numpy.ndarray'>
shaqe     -  (2, 3, 4)
dimension -  3
dtype     -  object

data - 
[[['1' '2' '3' '4']
  ['5' '6' '7' '8']
  ['9' '10' '11' '12']]

 [['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']
  ['i' 'j' 'j' 'l']]]


In [63]:
print('3 * 4 의 배열을 2개 생성')
ary = np.array([[[1,2,3,4] , [5,6,7,8] , [9,10,11,12]], [['a','b','c','d'] , ['e','f','g','h'] , ['i','j','j','l']]])

aryinfo(ary)
print('len() - ' , len(ary))
print('len() - ' , len(ary[0]))

print('len() - ' , len(ary[0][0]))

3 * 4 의 배열을 2개 생성
type      -  <class 'numpy.ndarray'>
shaqe     -  (2, 3, 4)
dimension -  3
dtype     -  <U11

data - 
[[['1' '2' '3' '4']
  ['5' '6' '7' '8']
  ['9' '10' '11' '12']]

 [['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']
  ['i' 'j' 'j' 'l']]]
len() -  2
len() -  3
len() -  4


- 인덱싱과 슬라이싱

In [80]:
ary = np.array([1,2,3,4,5,6,7,8,9])
aryinfo(ary)
print('indexing - ' , ary[0] , ary[-1])
print('slicing - '  , ary[4:7] )
print(ary[[0, 2]])

masking = [True , False , True , False , False , False , False , False , False ]
print(ary[masking])


type      -  <class 'numpy.ndarray'>
shaqe     -  (9,)
dimension -  1
dtype     -  int32

data - 
[1 2 3 4 5 6 7 8 9]
indexing -  1 9
slicing -  [5 6 7]
[1 3]
[1 3]


In [101]:
ary = np.array([[1,2,3],[4,5,6]])
aryinfo(ary)
print('첫번째 행의 첫번째 열의 값을 추출 - ' , ary[0][0] , ary[0,0])
print('두번째 행의 첫번째 열 - ' , ary[1][0] , ary[1,0])
print('마지막 행의 마지막 열 - ' , ary[-1][-1])
print('첫번째 행의 전체 열 - ' , ary[0])
print('두번째 열의 전체 행 - ' , ary[: , 1])
print('두번째 행의 두번째부터 끝까지 - ' , ary[1 , 1:])


type      -  <class 'numpy.ndarray'>
shaqe     -  (2, 3)
dimension -  2
dtype     -  int32

data - 
[[1 2 3]
 [4 5 6]]
첫번째 행의 첫번째 열의 값을 추출 -  1 1
두번째 행의 첫번째 열 -  4 4
마지막 행의 마지막 열 -  6
첫번째 행의 전체 열 -  [1 2 3]
두번째 열의 전체 행 -  [2 5]
두번째 행의 두번째부터 끝까지 -  [5 6]


- fancy indexing == arrayindexing
- 정수 배열 인덱싱
- bollean 인덱싱

In [108]:
ary = np.array([0,1,2,3,4,5,6,7,8,9])
print('짝수의 원소를 추출 - ')

# for i in ary :
#     if i > 0 and i % 2 == 0 :
#         print(i)
        
print('boolean indexing - ' , ary[ary % 2 == 0])
evenidx = np.array([1,3,5,7,9])
oddidx  = np.array([0,2,4,6,8])

print('정수 배열 인덱싱 - ' , ary[oddidx])

짝수의 원소를 추출 - 
boolean indexing -  [0 2 4 6 8]
정수 배열 인덱싱 -  [0 2 4 6 8]


In [120]:
ary = np.arange(1, 21)
aryinfo(ary)
print()
print('3의 배수만 추출 - ')
print('4로 나누면 1이 남는  수를 추출 - ')
print('3의 배수이고 4로 나누면 1이 남는 수를 추출')
print()
print(ary[ary % 3 == 0])
print(ary[ary % 4 == 1])
print(ary[(ary % 3 == 0)&(ary % 4 == 1)])

type      -  <class 'numpy.ndarray'>
shaqe     -  (20,)
dimension -  1
dtype     -  int32

data - 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

3의 배수만 추출 - 
4로 나누면 1이 남는  수를 추출 - 
3의 배수이고 4로 나누면 1이 남는 수를 추출

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]


array([9])

- reshape() : 배열의 변형

In [224]:
ary = np.arange(1,13).reshape(3,4)
aryinfo(ary)
print()
col_idx = [0,3]
print(ary[: , col_idx])
print('위 코드를 boolean 인덱싱으로 - ')

boolean_col_idx = [True , False , True , False]
print(ary[ : , boolean_col_idx])
print('5추출' , ary[1,0] , type(ary[1,0]))
print('5추출' , ary[1:2,0:1] , type(ary[1:2,0:1]))
print()
print('[[2][10]] 추출 - ' , ary[[0,2] , 1:2])
print('[[1 3][9 11]] 추출 - ' , ary[[0,2] , 0:3])

row_idx = np.array([0,2])
col_idx = np.array([0,2])

print(ary[[row_idx]][:,col_idx])

print('numpy ix_() 함수')
print( ary[np.ix_(row_idx , col_idx)])


ary[[0,2]][:,[0,2]]

type      -  <class 'numpy.ndarray'>
shaqe     -  (3, 4)
dimension -  2
dtype     -  int32

data - 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]
위 코드를 boolean 인덱싱으로 - 
[[ 1  3]
 [ 5  7]
 [ 9 11]]
5추출 5 <class 'numpy.int32'>
5추출 [[5]] <class 'numpy.ndarray'>

[[2][10]] 추출 -  [[ 2]
 [10]]
[[1 3][9 11]] 추출 -  [[ 1  2  3]
 [ 9 10 11]]
[[ 1  3]
 [ 9 11]]
numpy ix_() 함수
[[ 1  3]
 [ 9 11]]


C:\Users\a\AppData\Local\Temp\ipykernel_3504\48522379.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(ary[[row_idx]][:,col_idx])


array([[ 1,  3],
       [ 9, 11]])

- dtype : b -> boolean , i -> int , u8 -> unsigned(부호없는 정수) , f -> float , U -> UNICODE(문자열)

In [227]:
ary = np.array([1,2,3] , dtype = 'f')
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (3,)
dimension -  1
dtype     -  float32

data - 
[1. 2. 3.]


In [228]:
ary = np.array([1,2,3] , dtype = 'U')
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (3,)
dimension -  1
dtype     -  <U1

data - 
['1' '2' '3']


In [229]:
ary = np.array([1,2,3] , dtype = 'i')
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (3,)
dimension -  1
dtype     -  int32

data - 
[1 2 3]


In [232]:
ary = np.array([1,2,3] , dtype = 'u8')
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (3,)
dimension -  1
dtype     -  uint64

data - 
[1 2 3]


In [233]:
ary = np.array([-1,-2,3] , dtype = 'u8')
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (3,)
dimension -  1
dtype     -  uint64

data - 
[18446744073709551615 18446744073709551614                    3]


In [235]:
ary = np.array([1,2,3] , dtype = 'i8')
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (3,)
dimension -  1
dtype     -  int64

data - 
[1 2 3]


- inf(infinity) , nan (not a number)

In [239]:
print('infinity' , np.log(0))
print('infinity' , np.array([1,0]) / np.array([0,0]))

infinity -inf
infinity [inf nan]


C:\Users\a\AppData\Local\Temp\ipykernel_3504\656805303.py:1: RuntimeWarning: divide by zero encountered in log
  print('infinity' , np.log(0))
C:\Users\a\AppData\Local\Temp\ipykernel_3504\656805303.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print('infinity' , np.array([1,0]) / np.array([0,0]))
C:\Users\a\AppData\Local\Temp\ipykernel_3504\656805303.py:2: RuntimeWarning: invalid value encountered in true_divide
  print('infinity' , np.array([1,0]) / np.array([0,0]))


- 배열 생성 : array() , arange() , zeros() , ones() , zeros_like() , ones_like() , empty() , linspace() , logspace()

In [240]:
ary = np.zeros(5)
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (5,)
dimension -  1
dtype     -  float64

data - 
[0. 0. 0. 0. 0.]


In [241]:
ary = np.ones(5)
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shaqe     -  (5,)
dimension -  1
dtype     -  float64

data - 
[1. 1. 1. 1. 1.]


In [244]:
ary = np.zeros((3,5,2) , dtype = 'i')
aryinfo(ary)

type      -  <class 'numpy.ndarray'>
shape     -  (3, 5, 2)
dimension -  3
dtype     -  int32

data - 
[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [246]:
ary_copy = np.zeros_like(ary)
aryinfo(ary_copy)

type      -  <class 'numpy.ndarray'>
shape     -  (3, 5, 2)
dimension -  3
dtype     -  int32

data - 
[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [252]:
ary = np.empty((4 , 3) , dtype = 'f8')
aryinfo(ary)


# 배열 무작정 생성시 쓰레기 값이 들어간다.


type      -  <class 'numpy.ndarray'>
shape     -  (4, 3)
dimension -  2
dtype     -  float64

data - 
[[4.24399158e-314 8.48798317e-314 1.27319747e-313]
 [1.69759663e-313 2.12199579e-313 2.54639495e-313]
 [4.24399158e-314 8.48798317e-314 1.27319747e-313]
 [1.69759663e-313 2.12199579e-313 2.54639495e-313]]


In [254]:
ary = np.arange(3, 21 , 2)
ary

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [257]:
np.linspace(0 , 100 , 5)

array([  0.,  25.,  50.,  75., 100.])

In [258]:
np.logspace(0.1 , 1 , 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

- transpose matrix (전치행렬)
- T

In [268]:
ary = np.arange(1, 7).reshape(2,3)
aryinfo(ary)

ary_transpose = ary.T
aryinfo(ary_transpose)

type      -  <class 'numpy.ndarray'>
shape     -  (2, 3)
dimension -  2
dtype     -  int32

data - 
[[1 2 3]
 [4 5 6]]
type      -  <class 'numpy.ndarray'>
shape     -  (3, 2)
dimension -  2
dtype     -  int32

data - 
[[1 4]
 [2 5]
 [3 6]]


In [282]:
print('1차원 배열에 대한 전치행렬이 필요한 경우가 발생')
ary = np.arange(1 , 7)
aryinfo(ary)
ary_transpose = ary.reshape(1 , 6).T
aryinfo(ary_transpose)


1차원 배열에 대한 전치행렬이 필요한 경우가 발생
type      -  <class 'numpy.ndarray'>
shape     -  (6,)
dimension -  1
dtype     -  int32

data - 
[1 2 3 4 5 6]
type      -  <class 'numpy.ndarray'>
shape     -  (6, 1)
dimension -  2
dtype     -  int32

data - 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


- 다차원 배열을 1차원으로 만들어야한다면?
- flatten()


In [283]:
aryinfo(ary_transpose.flatten())

type      -  <class 'numpy.ndarray'>
shape     -  (6,)
dimension -  1
dtype     -  int32

data - 
[1 2 3 4 5 6]


- 배열 사용시 주의점(차원에 대한 주의가 필요함!!)

In [296]:
ary = np.arange(10)
aryinfo(ary)
print('reshape - ' , ary.reshape(1 , 10))
print('reshape - ' , ary.reshape(10 , 1))
print()
print('차원의 변경이 아닌 차원 증가를 위해서는 - newaxis')
print(ary[np.newaxis , :])
print(ary[ : , np.newaxis])

type      -  <class 'numpy.ndarray'>
shape     -  (10,)
dimension -  1
dtype     -  int32

data - 
[0 1 2 3 4 5 6 7 8 9]
reshape -  [[0 1 2 3 4 5 6 7 8 9]]
reshape -  [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

차원의 변경이 아닌 차원 증가를 위해서는 - newaxis
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


- ndarray(배열) 모든 원소에 대해서 순차적으로 접근해야하는 경우
- iternext() , finished 

In [298]:
ary = np.arange(10)
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [310]:
for tmp in ary :
    print(tmp , end = "\t")
    
print()
print()

for idx in range(len(ary)) :
    print(idx , end = "\t")

0	1	2	3	4	5	6	7	8	9	

0	1	2	3	4	5	6	7	8	9	

#### 대용량 데이터를 다룰때 편하다.

In [309]:
print('1차원 ndarray 에 대한 순차 접근 - ')
iter = np.nditer(ary , flags = ['c_index'])
while not iter.finished : 
    idx = iter.index
    print('idx - ' , idx , ary[idx] , end = '\t')
    iter.iternext()

1차원 ndarray 에 대한 순차 접근 - 
idx -  0 0	idx -  1 1	idx -  2 2	idx -  3 3	idx -  4 4	idx -  5 5	idx -  6 6	idx -  7 7	idx -  8 8	idx -  9 9	

In [358]:
print('2차원 ndarray 대한 iterator - ')

ary = ary.reshape(2,5)+1
ary

2차원 ndarray 대한 iterator - 


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [323]:
for i in range(len(ary)) :
    for f in ary[i] :
        print(f , end = '\t')

0	1	2	3	4	5	6	7	8	9	

In [335]:
iter = np.nditer(ary , flags = ['c_index'])
while not iter.finished :
    idx = iter.index
    print('idx - ' , idx , end = '\t')
    iter.iternext()

idx -  0	idx -  1	idx -  2	idx -  3	idx -  4	idx -  5	idx -  6	idx -  7	idx -  8	idx -  9	

In [360]:
print(ary.shape)
print(ary.shape[0])
print(ary.shape[1])
for row in range(ary.shape[0]) :
    for col in range(ary.shape[1]) :
        print(ary[row][col] , end = "\t")
    print()

(2, 5)
2
5
1	2	3	4	5	
6	7	8	9	10	


In [398]:
print('nditer - ')
iter = np.nditer(ary , flags = ['multi_index'])
while not iter.finished :
    idx = iter.multi_index
    if idx[1] == 4 :
        print(ary[idx] , end = '\t')
        print()
    else :
        print(ary[idx] , end = '\t')
    iter.iternext()
    
cnt = 0
iter = np.nditer(ary , flags = ['multi_index'])
while not iter.finished :
    idx = iter.multi_index
    if idx[0] == 0 :
        print(ary[idx] , end = '\t')
        cnt = cnt + 1
        if cnt % 5 == 0 :
            print()
    else :
        print(ary[idx] , end = '\t')
    iter.iternext()
    

nditer - 
1	2	3	4	5	
6	7	8	9	10	
1	2	3	4	5	
6	7	8	9	10	

In [373]:
tuple(idx)

(1, 4)

In [389]:
idx

(1, 4)